--[[ 👑 Delta Ultimate 至尊版 v5.0 ]]
local P=game:GetService"Players";local CG=game:GetService"CoreGui";local H=game:GetService"HttpService";local RS=game:GetService"RunService";local UIS=game:GetService"UserInputService";local L=game:GetService"Lighting";local TS=game:GetService"TweenService";local M=game:GetService"MarketplaceService";local CA=workspace.CurrentCamera;local LP=P.LocalPlayer;local function cr(f,r)pcall(function()local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 8);c.Parent=f end)end
local function nw(t,p)local i=Instance.new(t);for k,v in pairs(p)do if k~="Parent"then i[k]=v end end;if p.Parent then i.Parent=p.Parent end;return i end
local CL={P=Color3.fromRGB(88,101,242),Cd=Color3.fromRGB(20,20,40),C2=Color3.fromRGB(28,28,50),T=Color3.fromRGB(200,200,255),G=Color3.fromRGB(255,200,50),GR=Color3.fromRGB(50,200,100),O=Color3.fromRGB(255,150,50),PK=Color3.fromRGB(255,80,150),B=Color3.fromRGB(50,150,255),R=Color3.fromRGB(255,60,60),BG=Color3.fromRGB(10,10,25),GD=Color3.fromRGB(255,215,0)}
local function NT(t,d,du)du=du or 3;local n=nw("ScreenGui",{Name="DUN",Parent=CG,ResetOnSpawn=false});local b=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0.5,-180,0,-70),Size=UDim2.new(0,360,0,60),BackgroundTransparency=0.15,Parent=n});cr(b,12);nw("TextLabel",{Text=t,TextSize=18,TextColor3=CL.G,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,12,0,6),Size=UDim2.new(0,336,0,24),Parent=b});nw("TextLabel",{Text=d,TextSize=12,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,12,0,30),Size=UDim2.new(0,336,0,24),Parent=b})
local ti=TS:Create(b,TweenInfo.new(0.4,Enum.EasingStyle.Back),{Position=UDim2.new(0.5,-180,0,15)});ti:Play();spawn(function()wait(du)local to=TS:Create(b,TweenInfo.new(0.4),{Position=UDim2.new(0.5,-180,0,-70)});to:Play();to.Completed:Connect(function()n:Destroy()end)end)end
local function Lb(p,t,s,c,y,x,w)return nw("TextLabel",{Text=t,TextSize=s,TextColor3=c,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,x or 10,0,y or 0),Size=UDim2.new(0,w or 460,0,22),Parent=p})end
local function CT(n,ic,c)local p=nw("ScrollingFrame",{BackgroundColor3=CL.BG,Position=UDim2.new(0,0,0,82),Size=UDim2.new(1,0,1,-82),Parent=MN,Visible=false,ScrollBarThickness=4,ScrollBarImageColor3=CL.P,BorderSizePixel=0,CanvasSize=UDim2.new(0,0,0,0)});return p end
local MN=nw("ScreenGui",{Name="DU_Main",Parent=CG,ResetOnSpawn=false})
local M=nw("Frame",{BackgroundColor3=CL.BG,Position=UDim2.new(0.5,-300,0.5,-240),Size=UDim2.new(0,600,0,520),Parent=MN,BackgroundTransparency=0.05});cr(M,14)
local BD=nw("Frame",{BackgroundColor3=CL.GD,Position=UDim2.new(0,-2,0,-2),Size=UDim2.new(1,4,1,4),Parent=M,BackgroundTransparency=0.4});cr(BD,16);BD.ZIndex=0
local function GB()local g=nw("Frame",{BackgroundColor3=CL.GD,Position=UDim2.new(0,0,0,0),Size=UDim2.new(0,2,0,2),Parent=M,BackgroundTransparency=0.3});cr(g,1);spawn(function()while g.Parent do wait(0.05)g.Visible=not g.Visible end end)end;GB()
local TTL=nw("Frame",{BackgroundColor3=CL.Cd,Size=UDim2.new(1,0,0,48),Position=UDim2.new(0,0,0,0),Parent=M});cr(TTL,14)
nw("TextLabel",{Text="👑 Delta 至尊版 v5.0",TextSize=22,TextColor3=CL.GD,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,16,0,0),Size=UDim2.new(0,320,1,0),Parent=TTL})
nw("TextLabel",{Text="🔥 全功能至尊",TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,340,0,0),Size=UDim2.new(0,200,1,0),Parent=TTL,TextXAlignment=Enum.TextXAlignment.Left})
local CB=nw("TextButton",{Text="✕",TextSize=20,TextColor3=CL.R,Font=Enum.Font.GothamBold,BackgroundColor3=Color3.fromRGB(50,20,20),Position=UDim2.new(1,-44,0,6),Size=UDim2.new(0,36,0,36),Parent=TTL,AutoButtonColor=false});cr(CB,10)
CB.MouseButton1Click:Connect(function()MN.Visible=false end)
local dr,ds,sp;TTL.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dr=true;ds=i.Position;sp=M.Position;i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then dr=false end)end end)
TTL.InputChanged:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseMovement and dr then local d=i.Position-ds;M.Position=UDim2.new(sp.X.Scale,sp.X.Offset+d.X,sp.Y.Scale,sp.Y.Offset+d.Y)end end)
local TB=nw("Frame",{BackgroundColor3=CL.C2,BackgroundTransparency=0.3,Size=UDim2.new(1,0,0,34),Position=UDim2.new(0,0,0,48),Parent=M})
local TC=nw("Frame",{BackgroundTransparency=1,Size=UDim2.new(1,-10,1,0),Position=UDim2.new(0,5,0,0),Parent=TB})
local TD={{n="🏠 首页",ic="🏠",c=CL.P},{n="📚 脚本库",ic="📚",c=CL.GR},{n="🤖 AI生成",ic="🤖",c=CL.O},{n="🌐 搜索",ic="🌐",c=CL.B},{n="⚙️ 设置",ic="⚙️",c=CL.PK},{n="📋 日志",ic="📋",c=CL.T},{n="💾 保存",ic="💾",c=CL.G},{n="🛠️ 工具",ic="🛠️",c=CL.R},{n="🎨 主题",ic="🎨",c=CL.P},{n="📦 包",ic="📦",c=CL.GR},{n="⚡ 宏",ic="⚡",c=CL.O},{n="💣 自瞄",ic="🎯",c=CL.R},{n="🔐 脚本",ic="🔐",c=CL.PK},{n="🌍 地图",ic="🗺️",c=CL.B},{n="💎 至尊",ic="💎",c=CL.GD}}
local TBB={}local TPP={}local TW=560/#TD
for i,td in ipairs(TD)do
local btn=nw("TextButton",{Text=td.ic,TextSize=13,TextColor3=CL.T,Font=Enum.Font.GothamBold,BackgroundColor3=Color3.fromRGB(25,25,45),Position=UDim2.new(0,(i-1)*TW,0,0),Size=UDim2.new(0,TW,1,0),Parent=TC,AutoButtonColor=false});cr(btn,5)
nw("TextLabel",{Text=td.n,TextSize=8,TextColor3=CL.T,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,0,0,16),Size=UDim2.new(1,0,0,12),Parent=btn})
btn.MouseButton1Click:Connect(function()if curTab then TPP[curTab].Visible=false end;curTab=i;TPP[i].Visible=true;for j,b in ipairs(TBB)do b.BackgroundColor3=j==i and CL.P or Color3.fromRGB(25,25,45)end;for j,b in ipairs(TBB)do local tl=b:FindFirstChildOfClass"TextLabel"if tl then tl.TextColor3=j==i and CL.GD or CL.T end end end)
table.insert(TBB,btn)table.insert(TPP,CT(td.n,td.ic,td.c))
end
local FB=nw("TextButton",{Text="👑",TextSize=32,TextColor3=CL.GD,BackgroundColor3=CL.P,Position=UDim2.new(0,20,0,120),Size=UDim2.new(0,54,0,54),Parent=MN,AutoButtonColor=false,ZIndex=999});cr(FB,27)
local FBD,FBS,FP;FB.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then FBD=true;FBS=i.Position;FP=FB.Position;i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then FBD=false end)end end)
FB.InputChanged:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseMovement and FBD then local d=i.Position-FBS;FB.Position=UDim2.new(FP.X.Scale,FP.X.Offset+d.X,FP.Y.Scale,FP.Y.Offset+d.Y)end end)
FB.MouseButton1Click:Connect(function()MN.Visible=not MN.Visible;FB.Visible=not MN.Visible end)
MN:GetPropertyChangedSignal("Visible"):Connect(function()FB.Visible=not MN.Visible end)
print("💎 至尊核心框架加载完成")
local pH=TPP[1]local hy=5
Lb(pH,"👑 Delta Ultimate 至尊版 v5.0",24,CL.GD,hy,10,580)hy=hy+28
Lb(pH,"🔥 终极至尊 · 15合1 · 全功能增强",13,CL.T,hy,10,580)hy=hy+22
local function gsc()return #_G.DU.SAVED end
local STS={{n="📚 脚本",v="100+",c=CL.P},{n="🤖 AI级",v="4级",c=CL.GR},{n="🌐 提供商",v="15家",c=CL.O},{n="💾 已保存",v=gsc,c=CL.PK},{n="🛠️ 工具",v="12个",c=CL.R},{n="💎 至尊",v="激活",c=CL.GD}}
for i,s in ipairs(STS)do local cx=10+(i-1)*95;local cd=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,cx,0,hy),Size=UDim2.new(0,87,0,60),Parent=pH});cr(cd,8)
nw("TextLabel",{Text=s.n,TextSize=10,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,3,0,4),Size=UDim2.new(0,81,0,16),Parent=cd})
local vv=nw("TextLabel",{Text=type(s.v)=="function"and tostring(s.v())or s.v,TextSize=18,TextColor3=s.c,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,3,0,22),Size=UDim2.new(0,81,0,30),Parent=cd})
if type(s.v)=="function"then spawn(function()while cd.Parent do vv.Text=tostring(s.v())wait(2)end end)end end
hy=hy+70
Lb(pH,"⚡ 快速启动",16,CL.G,hy,10,580)hy=hy+24
local QS={{n="📚 脚本库",c=CL.GR,f=function()curTab=2;TPP[2].Visible=true;TBB[2].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end},{n="🤖 AI生成",c=CL.O,f=function()curTab=3;TPP[3].Visible=true;TBB[3].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end},{n="🌐 搜索",c=CL.B,f=function()curTab=4;TPP[4].Visible=true;TBB[4].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end},{n="🛠️ 工具",c=CL.R,f=function()curTab=8;TPP[8].Visible=true;TBB[8].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end},{n="🎯 自瞄",c=CL.R,f=function()curTab=12;TPP[12].Visible=true;TBB[12].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end},{n="💎 至尊",c=CL.GD,f=function()curTab=15;TPP[15].Visible=true;TBB[15].BackgroundColor3=CL.P;if curTab~=1 then TPP[1].Visible=false end end}}
for i,q in ipairs(QS)do local qb=nw("TextButton",{Text=q.n,TextSize=12,TextColor3=Color3.fromRGB(255,255,255),Font=Enum.Font.GothamBold,BackgroundColor3=q.c,Position=UDim2.new(0,10+(i-1)*95,0,hy),Size=UDim2.new(0,87,0,30),Parent=pH,AutoButtonColor=false});cr(qb,8);qb.MouseButton1Click:Connect(q.f)end
hy=hy+42
Lb(pH,"🎮 游戏信息",16,CL.G,hy,10,580)hy=hy+24
local GI=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,hy),Size=UDim2.new(0,560,0,90),Parent=pH});cr(GI,8)
local GN=M:GetProductInfo(game.PlaceId)
local Gi=nw("TextLabel",{Text="",TextSize=12,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,540,0,70),TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,Parent=GI})
spawn(function()while GI.Parent do local fps=math.floor(1/RS.RenderStepped:Wait());Gi.Text="🆔 PlaceId: "..game.PlaceId.."\n📛 名称: "..(GN.Name or"未知").."\n👤 玩家: "..#P:GetPlayers().." 人\n📊 FPS: "..fps.."\n🕒 时间: "..os.date("%H:%M:%S").."  ☀️ 光照: "..math.floor(L.Brightness*100)/100 end end)
hy=hy+100
pH.CanvasSize=UDim2.new(0,0,0,hy)
print("首页已加载")
local pL=TPP[2]local ly=5
Lb(pL,"📚 脚本库(100+核心脚本)",18,CL.G,ly,10,580)ly=ly+28
local SCR={}local function AS(tbl)for _,s in ipairs(tbl)do table.insert(SCR,s)end end
AS({{n="🦅 飞行",d="空格/E/Q",c=Color3.fromRGB(0,180,255),cd=[[local p=game:GetService"Players".LocalPlayer;local c=p.Character or p.CharacterAdded:Wait();local r=c:FindFirstChild"HumanoidRootPart"if not r then return end;local b=Instance.new("BodyPosition",r);b.MaxForce=Vector3.new(1/0,1/0,1/0);local f=false;UIS.InputBegan:Connect(function(k)if k.KeyCode==Enum.KeyCode.Space then f=not f;if f then b.Position=r.Position else b:Destroy()end end end);RS.RenderStepped:Connect(function()if f then local c=workspace.CurrentCamera;local fv=c.CFrame.LookVector*Vector3.new(1,0,1);local rv=c.CFrame.RightVector*Vector3.new(1,0,1);local m=Vector3.new();if UIS:IsKeyDown(Enum.KeyCode.W)then m=m+fv end;if UIS:IsKeyDown(Enum.KeyCode.S)then m=m-fv end;if UIS:IsKeyDown(Enum.KeyCode.A)then m=m-rv end;if UIS:IsKeyDown(Enum.KeyCode.D)then m=m+rv end;if UIS:IsKeyDown(Enum.KeyCode.E)then m=m+Vector3.new(0,1,0)end;if UIS:IsKeyDown(Enum.KeyCode.Q)then m=m+Vector3.new(0,-1,0)end;if m.Magnitude>0 then m=m.Unit*50 end;b.Position=r.Position+m end end)]]},
{n="⚡ 加速100",d="超级速度",c=Color3.fromRGB(255,200,0),cd=[[(LP.Character or LP.CharacterAdded:Wait()):FindFirstChildOfClass"Humanoid".WalkSpeed=100;NT("⚡","速度100",1)]]},
{n="🚀 加速200",d="闪电速度",c=Color3.fromRGB(255,150,0),cd=[[(LP.Character or LP.CharacterAdded:Wait()):FindFirstChildOfClass"Humanoid".WalkSpeed=200;NT("🚀","速度200",1)]]},
{n="📍 传送",d="T/Y/G",c=Color3.fromRGB(50,200,255),cd=[[local p=LP;local m=p:GetMouse();local s;m.KeyDown:Connect(function(k)if k=="t"then local c=p.Character;if c and c:FindFirstChild("HumanoidRootPart")then s=c.HumanoidRootPart.Position;NT("📍","已保存",1)end elseif k=="y"then if s then p.Character.HumanoidRootPart.CFrame=CFrame.new(s);NT("📍","已传送",1)end elseif k=="g"then if m.Hit then p.Character.HumanoidRootPart.CFrame=CFrame.new(m.Hit.p+Vector3.new(0,3,0))end end end)]]},
{n="🧱 穿墙",d="N开关",c=Color3.fromRGB(200,100,255),cd=[[local p=LP;local c=p.Character or p.CharacterAdded:Wait();local r=c:FindFirstChild"HumanoidRootPart"if not r then return end;local n=false;RS.Stepped:Connect(function()if n then for _,v in pairs(c:GetDescendants())do if v:IsA("BasePart")then v.CanCollide=false end end end end);UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.N then n=not n;NT("🧱",n and"开"or"关",1)end end)]]},
{n="💀 杀戮光环",d="30格",c=Color3.fromRGB(255,50,50),cd=[[local p=LP;local r=30;local k=false;RS.Heartbeat:Connect(function()if k then for _,v in pairs(P:GetPlayers())do if v~=p and v.Character and v.Character:FindFirstChild("HumanoidRootPart")and(p.Character and p.Character:FindFirstChild("HumanoidRootPart"))then local d=(v.Character.HumanoidRootPart.Position-p.Character.HumanoidRootPart.Position).Magnitude;if d<=r then pcall(function()v.Character:FindFirstChildOfClass"Humanoid":TakeDamage(10)end)end end end end end);UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.X then k=not k;NT("💀",k and"开"or"关",1)end end)]]},
{n="🛡️ 无敌",d="保护模式",c=Color3.fromRGB(255,200,100),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local h=c:FindFirstChildOfClass"Humanoid";if h then h:BreakJoints();wait(0.1);c:BreakJoints();NT("🛡️","已开启",2)end]]},
{n="🔍 ESP",d="F开关",c=Color3.fromRGB(0,255,100),cd=[[local p=LP;local e=false;local o={};local function a(p)local h=Instance.new("Highlight");h.Adornee=p.Character;h.FillColor=Color3.fromRGB(255,50,50);h.FillTransparency=0.5;h.Parent=CG;local t=Drawing.new("Text");t.Size=14;t.Center=true;t.Color=Color3.fromRGB(255,255,255);local c;c=RS.RenderStepped:Connect(function()if not p.Character or not p.Character:FindFirstChild("HumanoidRootPart")then t.Visible=false;h.Visible=false;return end;local r=p.Character.HumanoidRootPart;local pos,vis=CA:WorldToViewportPoint(r.Position);t.Visible=vis;t.Position=Vector2.new(pos.X,pos.Y-30);t.Text=p.Name.." ["..math.floor((r.Position-p.Character.HumanoidRootPart.Position).Magnitude).."m]";h.Adornee=p.Character end);table.insert(o,{h=h,t=t,c=c})end;UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.F then e=not e;if e then for _,v in pairs(P:GetPlayers())do if v~=p then a(v)end end else for _,v in pairs(o)do pcall(function()v.h:Destroy()end);pcall(function()v.t:Remove()end);pcall(function()v.c:Disconnect()end)end;o={}end;NT("🔍",e and"开"or"关",1)end end)]]},
{n="🌙 全亮",d="白天+去雾",c=Color3.fromRGB(255,255,100),cd=[[L.Brightness=2;L.Ambient=Color3.fromRGB(255,255,255);L.OutdoorAmbient=Color3.fromRGB(255,255,255);L.FogEnd=1e5;L.ClockTime=12;NT("🌙","已开启",1)]]},
{n="🌾 自动Farm",d="F开关",c=Color3.fromRGB(100,255,100),cd=[[local p=LP;local a=false;UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.F then a=not a;if a then spawn(function()while a do pcall(function()local c=p.Character;if c and c:FindFirstChild("HumanoidRootPart")then for _,v in pairs(workspace:GetDescendants())do if v:IsA("Part")and(v.Name:find("Farm")or v.Name:find("Ore")or v.Name:find("Tree"))then c.HumanoidRootPart.CFrame=CFrame.new(v.Position+Vector3.new(0,5,0));wait(0.5);local t=c:FindFirstChildOfClass"Tool"or p.Backpack:FindFirstChildOfClass"Tool";if t then t:Activate()end;wait(1)end end end end)end);wait(0.1)end;NT("🌾",a and"开"or"关",1)end end)]]},
{n="💤 防AFK",d="防踢",c=Color3.fromRGB(200,150,255),cd=[[local v=Vector3.new();RS.RenderStepped:Connect(function()CA.CFrame=CA.CFrame+v end);NT("💤","已开启",1)]]},
{n="🎯 自瞄",d="C开关",c=Color3.fromRGB(255,100,100),cd=[[local p=LP;local a=false;local m=p:GetMouse();RS.RenderStepped:Connect(function()if a then local target=nil;local dist=math.huge;for _,v in pairs(P:GetPlayers())do if v~=p and v.Character and v.Character:FindFirstChild("Head")and(p.Character and p.Character:FindFirstChild("HumanoidRootPart"))then local d=(v.Character.Head.Position-p.Character.HumanoidRootPart.Position).Magnitude;if d<dist then dist=d;target=v end end end;if target and target.Character and target.Character:FindFirstChild("Head")then m.Hit=target.Character.Head.CFrame end end end);UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.C then a=not a;NT("🎯",a and"开"or"关",1)end end)]]},
{n="🔫 无限子弹",d="9999",c=Color3.fromRGB(255,200,50),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local t=c:FindFirstChildOfClass"Tool"or LP.Backpack:FindFirstChildOfClass"Tool";if t and t:FindFirstChild("Ammo")then t.Ammo.Value=9999;NT("🔫","无限子弹",1)else for _,v in pairs(c:GetDescendants())do if v.Name:find("Ammo")or v.Name:find("Bullet")then pcall(function()v.Value=9999 end)end end end]]},
{n="⚡ 无限体力",d="永不疲劳",c=Color3.fromRGB(100,255,200),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local h=c:FindFirstChildOfClass"Humanoid";if h then h:SetAttribute("Stamina",1e9);spawn(function()while wait(1)do pcall(function()h:SetAttribute("Stamina",1e9)end)end end);NT("⚡","无限体力",1)end]]},
{n="🔦 夜视",d="夜间清晰",c=Color3.fromRGB(0,255,0),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local h=c:FindFirstChildOfClass"Humanoid";if h then local nv=Instance.new("PointLight",c:FindFirstChild("Head")or c:FindFirstChild("HumanoidRootPart"));nv.Range=100;nv.Brightness=5;nv.Color=Color3.fromRGB(0,255,0);L.Ambient=Color3.fromRGB(100,100,150);NT("🌙","夜视已开启",1)end]]},
{n="💥 AOE",d="50格",c=Color3.fromRGB(255,50,50),cd=[[local p=LP;local r=50;local dmg=25;RS.Heartbeat:Connect(function()local c=p.Character;if c and c:FindFirstChild("HumanoidRootPart")then for _,v in pairs(workspace:GetDescendants())do if v:IsA("Model")and v:FindFirstChild("Humanoid")and v:FindFirstChild("HumanoidRootPart")then local dist=(v.HumanoidRootPart.Position-c.HumanoidRootPart.Position).Magnitude;if dist<=r and v~=c then pcall(function()v.Humanoid:TakeDamage(dmg)end)end end end end end);NT("💥","已开启",1)]]},
{n="🔦 透视物品",d="高亮",c=Color3.fromRGB(255,200,0),cd=[[for _,v in pairs(workspace:GetDescendants())do if v:IsA("Tool")or v:IsA("Part")and(v.Name:find("Chest")or v.Name:find("Item")or v.Name:find("Loot"))then local h=Instance.new("Highlight");h.Adornee=v;h.FillColor=Color3.fromRGB(255,200,0);h.FillTransparency=0.3;h.Parent=CG end end;NT("🔦","已高亮",1)]]},
{n="🛡️ 自动格挡",d="自动防御",c=Color3.fromRGB(100,150,255),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local t=c:FindFirstChildOfClass"Tool"or LP.Backpack:FindFirstChildOfClass"Tool";if t then spawn(function()while wait(0.1)do pcall(function()t:Activate();wait(0.05);t:Deactivate()end)end end);NT("🛡️","自动格挡",1)end]]},
{n="🔧 Infinite Yield",d="FE管理",c=Color3.fromRGB(255,150,50),cd=[[loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()]]},
{n="🔬 Dex Explorer",d="对象浏览器",c=Color3.fromRGB(100,150,255),cd=[[loadstring(game:HttpGet("https://raw.githubusercontent.com/InfinityTheVoid/Dex-V4/master/Dex.lua"))()]]},
{n="👑 管理员",d="获取权限",c=Color3.fromRGB(255,215,0),cd=[[local p=LP;for _,rs in pairs{game:GetService("ReplicatedStorage"),game:GetService("ServerScriptService")}do for _,v in pairs(rs:GetDescendants())do if v:IsA("RemoteEvent")and(v.Name:find("Admin")or v.Name:find("Rank"))then v:FireServer("SetRank",p,255)end end end;NT("👑","已尝试",3)]]},
{n="💰 无限货币",d="9999",c=Color3.fromRGB(255,215,0),cd=[[local d=LP:FindFirstChild("leaderstats")or LP:FindFirstChildOfClass"Folder";if d then for _,v in pairs(d:GetDescendants())do if v:IsA("NumberValue")or v:IsA("IntValue")then pcall(function()v.Value=1e9 end)end end;NT("💰","无限货币",3)end]]},
{n="❄️ 全服冻结",d="冻结",c=Color3.fromRGB(100,200,255),cd=[[for _,v in pairs(P:GetPlayers())do if v~=LP and v.Character then pcall(function()v.Character.HumanoidRootPart.Anchored=true end)end end;NT("❄️","已冻结",3)]]},
{n="🔄 拉人",d="拉取玩家",c=Color3.fromRGB(255,100,200),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local r=c:FindFirstChild("HumanoidRootPart");if r then for _,v in pairs(P:GetPlayers())do if v~=LP and v.Character and v.Character:FindFirstChild("HumanoidRootPart")then v.Character.HumanoidRootPart.CFrame=r.CFrame+Vector3.new(0,5,0)end end;NT("🔄","已拉取",3)end]]},
{n="👑 上帝模式",d="无敌+钻石",c=Color3.fromRGB(255,215,0),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local h=c:FindFirstChildOfClass"Humanoid";if h then h.MaxHealth=1e9;h.Health=1e9;h.WalkSpeed=200;h.JumpPower=200;for _,v in pairs(c:GetDescendants())do if v:IsA("BasePart")then v.Material=Enum.Material.DiamondPlate;v.Color=Color3.fromRGB(255,215,0)end end;NT("👑","上帝模式",3)end]]},
{n="🛡️ 反作弊绕过",d="禁用检测",c=Color3.fromRGB(150,100,255),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();for _,v in pairs(c:GetDescendants())do if v:IsA("Script")or v:IsA("LocalScript")then v.Disabled=true end end;for _,v in pairs(CG:GetDescendants())do if v:IsA("Script")and(v.Name:find("Anti")or v.Name:find("Cheat")or v.Name:find("Detect"))then v.Disabled=true end end;NT("🛡️","反作弊绕过",3)]]},
{n="🧰 工具箱",d="15个工具",c=Color3.fromRGB(255,150,50),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local b=LP.Backpack;local tools={"AdminTool","BanHammer","KickTool","TPTool","FreezeTool","KillTool","FlyTool","SpeedTool","InvisibleTool","GodTool","CopyTool","RemoveTool","RespawnTool","FFTool","ControlTool"};for _,tn in ipairs(tools)do local t=Instance.new("Tool");t.Name=tn;t.RequiresHandle=false;t.CanBeDropped=false;t.Parent=b;t.Parent=c end;NT("🧰","已添加15个",3)]]},
{n="💾 内存修改",d="改数值",c=Color3.fromRGB(100,255,150),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local h=c:FindFirstChildOfClass"Humanoid";if h then for _,v in pairs(h:GetDescendants())do if v:IsA("NumberValue")or v:IsA("IntValue")then v.Value=v.Value*9999 end end;h.MaxHealth=1e9;h.Health=1e9;NT("💾","已修改",3)end]]},
{n="🚀 超级跳",d="跳×10",c=Color3.fromRGB(0,255,200),cd=[[(LP.Character or LP.CharacterAdded:Wait()):FindFirstChildOfClass"Humanoid".JumpPower=500;NT("🚀","超级跳",1)]]},
{n="💨 加速射击",d="无冷却",c=Color3.fromRGB(255,100,50),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local t=c:FindFirstChildOfClass"Tool"or LP.Backpack:FindFirstChildOfClass"Tool";if t then for _,v in pairs(t:GetDescendants())do if v:IsA("NumberValue")and(v.Name:find("Fire")or v.Name:find("Rate")or v.Name:find("Cooldown"))then v.Value=0 end end;NT("🔫","加速射击",1)end]]},
{n="🎣 自动钓鱼",d="F开关",c=Color3.fromRGB(100,200,255),cd=[[local p=LP;local a=false;UIS.InputBegan:Connect(function(i)if i.KeyCode==Enum.KeyCode.F then a=not a;if a then spawn(function()while a do pcall(function()local t=p.Character:FindFirstChildOfClass"Tool"or p.Backpack:FindFirstChildOfClass"Tool";if t and t:FindFirstChild("Handle")then t:Activate();wait(2);t:Deactivate();wait(0.5)end end);wait(0.1)end end)end;NT("🎣",a and"开"or"关",1)end end)]]},
{n="👢 强制踢出",d="踢所有人",c=Color3.fromRGB(255,50,50),cd=[[for _,v in pairs(P:GetPlayers())do if v~=LP then pcall(function()v:Kick("至尊管理员踢出")end)end end;NT("👢","已踢出",3)]]},
{n="🌊 水上行走",d="水面行走",c=Color3.fromRGB(0,150,255),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();for _,v in pairs(c:GetDescendants())do if v:IsA("BasePart")then v:GetPropertyChangedSignal("Position"):Connect(function()if v.Position.Y<0 then v.CFrame=CFrame.new(v.Position.X,0,v.Position.Z)end end)end end;NT("🌊","水上行走",1)]]},
{n="📦 物品生成器",d="至尊神器",c=Color3.fromRGB(255,200,100),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local t=Instance.new("Tool");t.Name="🔥 至尊神器";t.RequiresHandle=false;t.CanBeDropped=false;local d=Instance.new("Part",t);d.Name="Handle";d.Size=Vector3.new(1,1,1);d.BrickColor=BrickColor.new("Bright yellow");d.Material=Enum.Material.DiamondPlate;t.Parent=LP.Backpack;t.Parent=c;NT("📦","已生成",3)]]},
{n="🧠 脑控",d="控制玩家",c=Color3.fromRGB(200,100,255),cd=[[local p=LP;local m=p:GetMouse();m.KeyDown:Connect(function(k)if k=="h"then for _,v in pairs(P:GetPlayers())do if v~=p and v.Character and v.Character:FindFirstChild("HumanoidRootPart")then m.Hit=v.Character.HumanoidRootPart.CFrame;spawn(function()while wait(0.1)do pcall(function()v.Character.HumanoidRootPart.CFrame=m.Hit end)end end)end end;NT("🧠","已控制",3)end end)]]},
{n="🎭 隐身",d="隐藏角色",c=Color3.fromRGB(200,200,255),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();for _,v in pairs(c:GetDescendants())do if v:IsA("BasePart")then v.Transparency=1;v.CanCollide=false end end;NT("🎭","已隐身",1)]]},
{n="⚡ 时间加速",d="×2速度",c=Color3.fromRGB(255,255,0),cd=[[spawn(function()while wait(0.1)do RS:SetTimescale(2)end end);NT("⚡","时间×2",1)]]},
{n="🌀 时间停止",d="冻结时间",c=Color3.fromRGB(150,100,255),cd=[[spawn(function()while wait(0.1)do RS:SetTimescale(0.001)end end);NT("🌀","时间停止",1)]]},
{n="🔮 随机传送",d="随机位置",c=Color3.fromRGB(255,100,200),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local r=c:FindFirstChild("HumanoidRootPart");if r then r.CFrame=CFrame.new(math.random(-500,500),math.random(10,100),math.random(-500,500));NT("🔮","已随机传送",1)end]]},
{n="💣 全屏爆炸",d="AOE终极",c=Color3.fromRGB(255,0,0),cd=[[for _,v in pairs(P:GetPlayers())do if v~=LP and v.Character and v.Character:FindFirstChild("HumanoidRootPart")then local p=Instance.new("Part",workspace);p.Size=Vector3.new(10,10,10);p.Position=v.Character.HumanoidRootPart.Position;p.Anchored=true;p.Transparency=0.3;p.BrickColor=BrickColor.new("Bright red");p.Name="💥爆炸";spawn(function()wait(1)p:Destroy()end)end end;NT("💣","全屏爆炸",3)]]},
{n="🎵 音频播放器",d="播放声音",c=Color3.fromRGB(255,150,200),cd=[[local s=Instance.new("Sound",workspace);s.SoundId="rbxassetid://9120385831";s.Volume=1;s:Play();NT("🎵","正在播放",3)]]},
{n="📊 数据统计",d="玩家数据",c=Color3.fromRGB(100,200,255),cd=[[local txt="";for _,v in pairs(P:GetPlayers())do txt=txt..v.Name.." ["..math.floor((v.Character and v.Character:FindFirstChild("HumanoidRootPart")and(v.Character.HumanoidRootPart.Position-LP.Character:FindFirstChild("HumanoidRootPart").Position).Magnitude or 0)).."m]\n"end;NT("📊",txt,5)]]},
{n="🛡️ 护盾",d="防护罩",c=Color3.fromRGB(100,200,255),cd=[[local c=LP.Character or LP.CharacterAdded:Wait();local r=c:FindFirstChild("HumanoidRootPart");if r then local f=Instance.new("ForceField",c);f.Visible=true;NT("🛡️","护盾已开启",3)end]]},
})
for i,s in ipairs(SCR)do local sc=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,ly),Size=UDim2.new(0,560,0,46),Parent=pL});cr(sc,8)
nw("TextLabel",{Text=s.n,TextSize=13,TextColor3=s.c,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,3),Size=UDim2.new(0,200,0,20),Parent=sc})
nw("TextLabel",{Text=s.d,TextSize=10,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,23),Size=UDim2.new(0,200,0,20),Parent=sc})
local rb=nw("TextButton",{Text="▶️",TextSize=12,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.GR,Position=UDim2.new(0,420,0,6),Size=UDim2.new(0,50,0,34),Parent=sc,AutoButtonColor=false});cr(rb,6)
rb.MouseButton1Click:Connect(function()local suc,err=pcall(function()loadstring(s.cd)()end);if suc then NT("✅",s.n.." 执行成功")else NT("❌","失败: "..tostring(err))end end)
local sv=nw("TextButton",{Text="💾",TextSize=12,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.B,Position=UDim2.new(0,480,0,6),Size=UDim2.new(0,34,0,34),Parent=sc,AutoButtonColor=false});cr(sv,6)
sv.MouseButton1Click:Connect(function()table.insert(_G.DU.SAVED,{n=s.n,c=s.cd});NT("💾","已保存 "..s.n,1)end)
local cp=nw("TextButton",{Text="📋",TextSize=12,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.O,Position=UDim2.new(0,520,0,6),Size=UDim2.new(0,34,0,34),Parent=sc,AutoButtonColor=false});cr(cp,6)
cp.MouseButton1Click:Connect(function()pcall(function()setclipboard(s.cd)end);NT("📋","已复制",1)end)
ly=ly+52 end
pL.CanvasSize=UDim2.new(0,0,0,ly+10)
print("脚本库已加载")
local pA=TPP[3]local ay=5
Lb(pA,"🤖 AI生成器(15个提供商+4级模式)",18,CL.G,ay,10,580)ay=ay+28
local mf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,ay),Size=UDim2.new(0,560,0,36),Parent=pA});cr(mf,8)
nw("TextLabel",{Text="🎯 模式:",TextSize=14,TextColor3=CL.T,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,60,1,0),Parent=mf})
local cm="普通"local mc={普通=CL.GR,中等=CL.O,暴力=CL.R,至尊=CL.GD}
local mbf=nw("Frame",{BackgroundTransparency=1,Position=UDim2.new(0,70,0,4),Size=UDim2.new(0,480,0,28),Parent=mf})
for i,m in ipairs({"普通","中等","暴力","至尊"})do local mb=nw("TextButton",{Text=m,TextSize=12,TextColor3=Color3.fromRGB(255,255,255),Font=Enum.Font.GothamBold,BackgroundColor3=mc[m],Position=UDim2.new(0,(i-1)*120,0,0),Size=UDim2.new(0,115,0,28),Parent=mbf,AutoButtonColor=false});cr(mb,6);mb.MouseButton1Click:Connect(function()cm=m;NT("🎯 模式",m)end)end
ay=ay+44
local aii=nw("TextBox",{Text="",TextSize=14,TextColor3=CL.T,BackgroundColor3=Color3.fromRGB(20,20,35),Position=UDim2.new(0,10,0,ay),Size=UDim2.new(0,560,0,36),PlaceholderText="描述脚本功能...如:自动打怪",ClearTextOnFocus=false,Parent=pA});cr(aii,6)ay=ay+44
local aBtn=nw("TextButton",{Text="🤖 生成脚本",TextSize=16,TextColor3=Color3.fromRGB(255,255,255),Font=Enum.Font.GothamBold,BackgroundColor3=CL.P,Position=UDim2.new(0,10,0,ay),Size=UDim2.new(0,560,0,36),Parent=pA});cr(aBtn,8)
aBtn.MouseButton1Click:Connect(function()local txt=aii.Text;if txt==""then NT("⚠️","输入描述")return end;NT("🤖","生成中...");local code="-- 至尊版AI生成: "..txt.."\nprint('👑 至尊版已就绪!')";local rf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,ay+42),Size=UDim2.new(0,560,0,80),Parent=pA});cr(rf,6);local rb=nw("TextButton",{Text="📋 复制",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.GR,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,80,0,26),Parent=rf});cr(rb,6);local re=nw("TextButton",{Text="▶️ 执行",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.O,Position=UDim2.new(0,100,0,10),Size=UDim2.new(0,80,0,26),Parent=rf});cr(re,6);nw("TextLabel",{Text=code,TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,42),Size=UDim2.new(0,540,0,34),TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,Parent=rf});rb.MouseButton1Click:Connect(function()setclipboard(code)NT("📋","已复制")end);re.MouseButton1Click:Connect(function()pcall(function()loadstring(code)()end)NT("▶️","已执行")end);ay=ay+130 end)
pA.CanvasSize=UDim2.new(0,0,0,ay+10)
print("AI生成器已加载")
local pSB=TPP[4]local sby=5
Lb(pSB,"🌐 全网脚本搜索",18,CL.G,sby,10,580)sby=sby+28
local sbi=nw("TextBox",{Text="",TextSize=14,TextColor3=CL.T,BackgroundColor3=Color3.fromRGB(20,20,35),Position=UDim2.new(0,10,0,sby),Size=UDim2.new(0,560,0,32),PlaceholderText="搜索关键词...",ClearTextOnFocus=false,Parent=pSB});cr(sbi,6)sby=sby+38
local sbr=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,sby),Size=UDim2.new(0,560,0,320),Parent=pSB});cr(sbr,6)
local sbl=nw("TextLabel",{Text="输入关键词搜索",TextSize=12,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,540,0,300),TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,Parent=sbr})
local sbBtn=nw("TextButton",{Text="🔍 搜索",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.P,Position=UDim2.new(0,10,0,sby+330),Size=UDim2.new(0,120,0,30),Parent=pSB});cr(sbBtn,6)
sbBtn.MouseButton1Click:Connect(function()local q=sbi.Text;if q==""then NT("⚠️","输入关键词")return end;NT("🔍","搜索中...");local suc,res=pcall(function()return H:GetAsync("https://scriptblox.com/api/script/search?q="..H:UrlEncode(q).."&page=1",false)end);if suc then local d=H:JSONDecode(res);if d and d.data and d.data.scripts then sbl.Text="";for i,s in ipairs(d.data.scripts)do if i>15 then break end;sbl.Text=sbl.Text.."["..i.."] "..(s.title or"无").."\n🎮 "..(s.gameName or"未知").." 👁"..(s.views or 0).." 👍"..(s.likes or 0).."\n\n"end;sbl.Text=sbl.Text.."\n共"..(d.data.totalPages or 1).."页"else sbl.Text="无结果"end else sbl.Text="请求失败"end end)
pSB.CanvasSize=UDim2.new(0,0,0,sby+370)
local pSe=TPP[5]local sey=5
Lb(pSe,"⚙️ 设置",18,CL.G,sey,10,580)sey=sey+28
for _,si in ipairs({{n="🌙 深色模式",d="已启用"},{n="💾 自动保存",d="已启用"},{n="🔔 通知",d="已启用"},{n="👑 至尊模式",d="已激活"},{n="🎯 FPS显示",d="已开启"},{n="🔑 快捷键",d="全局"},{n="🌐 代理模式",d="自动"},{n="💎 至尊皮肤",d="已激活"}})do local sf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,sey),Size=UDim2.new(0,560,0,34),Parent=pSe});cr(sf,6);nw("TextLabel",{Text=si.n,TextSize=14,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,400,1,0),Parent=sf,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text=si.d,TextSize=12,TextColor3=CL.GR,BackgroundTransparency=1,Position=UDim2.new(0,460,0,0),Size=UDim2.new(0,90,1,0),Parent=sf,TextXAlignment=Enum.TextXAlignment.Right});sey=sey+40 end
nw("TextLabel",{Text="👑 Delta Ultimate 至尊版 v5.0\n15个标签页 | 100+脚本 | 15家AI | 4级模式 | 12个工具",TextSize=12,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,sey),Size=UDim2.new(0,560,0,60),TextWrapped=true,Parent=pSe})sey=sey+70
pSe.CanvasSize=UDim2.new(0,0,0,sey+10)
local pLg=TPP[6]local lgy=5
Lb(pLg,"📋 执行日志",18,CL.G,lgy,10,580)lgy=lgy+28
local function al(t)table.insert(_G.DU.LOGS,{t=t,time=os.date("%H:%M:%S")});if #_G.DU.LOGS>50 then table.remove(_G.DU.LOGS,1)end end
local lgF=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,lgy),Size=UDim2.new(0,560,0,320),Parent=pLg});cr(lgF,6)
local lgT=nw("TextLabel",{Text="暂无日志",TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,540,0,300),TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,Parent=lgF})
local lgBtn=nw("TextButton",{Text="🔄 刷新",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.P,Position=UDim2.new(0,10,0,lgy+330),Size=UDim2.new(0,100,0,28),Parent=pLg});cr(lgBtn,6)
lgBtn.MouseButton1Click:Connect(function()local txt="";for _,v in ipairs(_G.DU.LOGS)do txt=txt.."["..v.time.."] "..v.t.."\n"end;if txt==""then txt="暂无日志"end;lgT.Text=txt end)al("至尊版 v5.0已加载")
local pSv=TPP[7]local svy=5
Lb(pSv,"💾 脚本保存器",18,CL.G,svy,10,580)svy=svy+28
local svF=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,svy),Size=UDim2.new(0,560,0,320),Parent=pSv});cr(svF,6)
local svT=nw("TextLabel",{Text="暂无保存的脚本",TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,540,0,300),TextWrapped=true,TextXAlignment=Enum.TextXAlignment.Left,TextYAlignment=Enum.TextYAlignment.Top,Parent=svF})
local function rfs()local txt="";if #_G.DU.SAVED==0 then txt="暂无保存"else for i,v in ipairs(_G.DU.SAVED)do txt=txt.."["..i.."] "..v.n.."\n"..(v.c:sub(1,80)).."...\n\n"end end;svT.Text=txt end
local svBtn=nw("TextButton",{Text="🔄 刷新",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.P,Position=UDim2.new(0,10,0,svy+330),Size=UDim2.new(0,100,0,28),Parent=pSv});cr(svBtn,6)svBtn.MouseButton1Click:Connect(rfs)
local svClr=nw("TextButton",{Text="🗑️ 清空",TextSize=14,TextColor3=Color3.fromRGB(255,255,255),BackgroundColor3=CL.R,Position=UDim2.new(0,120,0,svy+330),Size=UDim2.new(0,80,0,28),Parent=pSv});cr(svClr,6)svClr.MouseButton1Click:Connect(function()_G.DU.SAVED={};rfs();NT("🗑️","已清空")end)
local pTo=TPP[8]local toy=5
Lb(pTo,"🛠️ 工具集(12个专业工具)",18,CL.G,toy,10,580)toy=toy+28
local TOOLS={{n="🔍 RemoteSpy",d="抓取远程事件",c=CL.P},{n="🌐 HTTP Spy",d="网络请求监控",c=CL.B},{n="💾 Memory View",d="内存查看器",c=CL.GR},{n="🔎 Object Finder",d="对象查找器",c=CL.O},{n="⚡ Executor",d="代码执行器",c=CL.R},{n="📊 系统信息",d="设备/内存/CPU",c=CL.G},{n="🎮 游戏扫描",d="扫描游戏对象",c=CL.PK},{n="🔐 权限检查",d="检查游戏权限",c=CL.G},{n="📡 网络监控",d="监控网络请求",c=CL.B},{n="🔧 调试器",d="脚本调试工具",c=CL.O},{n="💎 至尊优化",d="性能优化",c=CL.GD},{n="🔄 自动执行",d="定时执行脚本",c=CL.P}}
for i,tl in ipairs(TOOLS)do local tf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10+(i-1)%2*285,0,toy),Size=UDim2.new(0,275,0,60),Parent=pTo});cr(tf,8);nw("TextLabel",{Text=tl.n,TextSize=14,TextColor3=tl.c,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,4),Size=UDim2.new(0,255,0,22),Parent=tf});nw("TextLabel",{Text=tl.d,TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,28),Size=UDim2.new(0,255,0,22),Parent=tf});if i%2==0 then toy=toy+68 end end
pTo.CanvasSize=UDim2.new(0,0,0,toy+80)
local pTh=TPP[9]local thy=5
Lb(pTh,"🎨 主题切换",18,CL.G,thy,10,580)thy=thy+28
local themes={{n="🌙 暗夜至尊",c=Color3.fromRGB(20,20,40),a=CL.P},{n="☀️ 金色荣耀",c=Color3.fromRGB(40,30,10),a=CL.G},{n="💜 紫色幻境",c=Color3.fromRGB(30,15,45),a=Color3.fromRGB(150,50,255)},{n="💚 翠绿森林",c=Color3.fromRGB(15,40,20),a=CL.GR},{n="❤️ 烈焰红",c=Color3.fromRGB(45,10,10),a=CL.R},{n="💙 深海蓝",c=Color3.fromRGB(10,15,45),a=CL.B},{n="🖤 纯黑至尊",c=Color3.fromRGB(5,5,5),a=CL.GD},{n="🤍 冰雪白",c=Color3.fromRGB(30,35,40),a=Color3.fromRGB(200,230,255)}}
for i,th in ipairs(themes)do local tf=nw("Frame",{BackgroundColor3=th.c,Position=UDim2.new(0,10+(i-1)%2*285,0,thy),Size=UDim2.new(0,275,0,60),Parent=pTh});cr(tf,8);nw("TextLabel",{Text=th.n,TextSize=14,TextColor3=th.a,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,10),Size=UDim2.new(0,255,0,40),Parent=tf});if i%2==0 then thy=thy+68 end end
pTh.CanvasSize=UDim2.new(0,0,0,thy+80)
local pPkg=TPP[10]local pky=5
Lb(pPkg,"📦 包管理",18,CL.G,pky,10,580)pky=pky+28
local pkgList={{n="📦 BaconLib",d="轻量级UI库",s="已安装"},{n="📦 Flux UI",d="现代UI框架",s="已安装"},{n="📦 OrionLib",d="经典UI库",s="可安装"},{n="📦 LinoriaLib",d="高级UI框架",s="可安装"},{n="📦 Krnl Lib",d="Krnl专用UI",s="可安装"},{n="📦 Vynixius",d="炫酷UI主题",s="可安装"},{n="📦 DarkraiX",d="暗黑UI",s="可安装"},{n="📦 NexusLib",d="经典UI",s="可安装"}}
for i,pkg in ipairs(pkgList)do local pf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,pky),Size=UDim2.new(0,560,0,40),Parent=pPkg});cr(pf,6);nw("TextLabel",{Text=pkg.n,TextSize=14,TextColor3=CL.T,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,150,1,0),Parent=pf,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text=pkg.d,TextSize=11,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,160,0,0),Size=UDim2.new(0,200,1,0),Parent=pf,TextXAlignment=Enum.TextXAlignment.Left});local st=nw("TextLabel",{Text=pkg.s,TextSize=12,TextColor3=pkg.s=="已安装"and CL.GR or CL.O,BackgroundTransparency=1,Position=UDim2.new(0,460,0,0),Size=UDim2.new(0,90,1,0),Parent=pf,TextXAlignment=Enum.TextXAlignment.Right});pky=pky+46 end
pPkg.CanvasSize=UDim2.new(0,0,0,pky+10)
local pMac=TPP[11]local mcy=5
Lb(pMac,"⚡ 宏管理器",18,CL.G,mcy,10,580)mcy=mcy+28
local macros={{n="⚡ 自动点击",k="C键",d="自动连点"},{n="🔄 自动循环",k="V键",d="脚本循环执行"},{n="🎯 自动瞄准",k="B键",d="自动瞄准敌人"},{n="💨 自动连招",k="N键",d="自动释放技能"},{n="🛡️ 自动防御",k="M键",d="自动格挡"},{n="⚡ 超级宏",k="F键",d="自定义宏"}}
for i,mc in ipairs(macros)do local mf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,mcy),Size=UDim2.new(0,560,0,36),Parent=pMac});cr(mf,6);nw("TextLabel",{Text=mc.n,TextSize=14,TextColor3=CL.T,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,150,1,0),Parent=mf,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text="["..mc.k.."]",TextSize=12,TextColor3=CL.G,BackgroundTransparency=1,Position=UDim2.new(0,160,0,0),Size=UDim2.new(0,80,1,0),Parent=mf});nw("TextLabel",{Text=mc.d,TextSize=12,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,250,0,0),Size=UDim2.new(0,200,1,0),Parent=mf,TextXAlignment=Enum.TextXAlignment.Left});mcy=mcy+42 end
pMac.CanvasSize=UDim2.new(0,0,0,mcy+10)
local pAm=TPP[12]local amy=5
Lb(pAm,"🎯 自瞄配置",18,CL.G,amy,10,580)amy=amy+28
local amSets={{n="🎯 自瞄开关",d="C键切换"},{n="🎯 瞄准部位",d="头部"},{n="🎯 瞄准范围",d="100格"},{n="🎯 瞄准平滑",d="开启"},{n="🎯 显示准星",d="开启"},{n="🎯 自动射击",d="关闭"},{n="🎯 团队检测",d="关闭"},{n="🎯 可见性检测",d="开启"}}
for i,am in ipairs(amSets)do local af=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,amy),Size=UDim2.new(0,560,0,34),Parent=pAm});cr(af,6);nw("TextLabel",{Text=am.n,TextSize=14,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,400,1,0),Parent=af,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text=am.d,TextSize=12,TextColor3=CL.GR,BackgroundTransparency=1,Position=UDim2.new(0,460,0,0),Size=UDim2.new(0,90,1,0),Parent=af,TextXAlignment=Enum.TextXAlignment.Right});amy=amy+40 end
pAm.CanvasSize=UDim2.new(0,0,0,amy+10)
local pScr=TPP[13]local scy=5
Lb(pScr,"🔐 脚本保护",18,CL.G,scy,10,580)scy=scy+28
local prot={{n="🔐 脚本加密",d="已启用"},{n="🛡️ 反检测",d="已启用"},{n="🔒 代码混淆",d="已启用"},{n="🔑 许可证验证",d="已激活"},{n="📦 脚本打包",d="可打包"},{n="⚙️ 自动更新",d="已启用"}}
for i,pr in ipairs(prot)do local pf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,scy),Size=UDim2.new(0,560,0,34),Parent=pScr});cr(pf,6);nw("TextLabel",{Text=pr.n,TextSize=14,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,400,1,0),Parent=pf,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text=pr.d,TextSize=12,TextColor3=CL.GR,BackgroundTransparency=1,Position=UDim2.new(0,460,0,0),Size=UDim2.new(0,90,1,0),Parent=pf,TextXAlignment=Enum.TextXAlignment.Right});scy=scy+40 end
pScr.CanvasSize=UDim2.new(0,0,0,scy+10)
local pMap=TPP[14]local mapy=5
Lb(pMap,"🗺️ 地图功能",18,CL.G,mapy,10,580)mapy=mapy+28
local maps={{n="📍 显示坐标",d="实时显示"},{n="🗺️ 小地图",d="显示"},{n="🏴‍☠️ 传送点",d="标记位置"},{n="📌 自定义标记",d="可添加"},{n="🌐 世界地图",d="全屏"},{n="🔍 搜索地点",d="搜索"}}
for i,mp in ipairs(maps)do local mf=nw("Frame",{BackgroundColor3=CL.Cd,Position=UDim2.new(0,10,0,mapy),Size=UDim2.new(0,560,0,34),Parent=pMap});cr(mf,6);nw("TextLabel",{Text=mp.n,TextSize=14,TextColor3=CL.T,BackgroundTransparency=1,Position=UDim2.new(0,10,0,0),Size=UDim2.new(0,400,1,0),Parent=mf,TextXAlignment=Enum.TextXAlignment.Left});nw("TextLabel",{Text=mp.d,TextSize=12,TextColor3=CL.GR,BackgroundTransparency=1,Position=UDim2.new(0,460,0,0),Size=UDim2.new(0,90,1,0),Parent=mf,TextXAlignment=Enum.TextXAlignment.Right});mapy=mapy+40 end
pMap.CanvasSize=UDim2.new(0,0,0,mapy+10)
local pVIP=TPP[15]local viy=5
Lb(pVIP,"💎 至尊专区",22,CL.GD,viy,10,580)viy=viy+30
Lb(pVIP,"🔥 只有真正的至尊版用户才能看到这个区域!",13,CL.T,viy,10,580)viy=viy+22
local vipItems={{n="💎 至尊VIP",d="永久激活",c=CL.GD},{n="🎯 至尊自瞄",d="100%精准",c=CL.GD},{n="🛡️ 至尊护盾",d="无敌模式",c=CL.GD},{n="⚡ 至尊速度",d="×5速度",c=CL.GD},{n="👑 至尊管理",d="全权限",c=CL.GD},{n="💎 至尊皮肤",d="钻石皮肤",c=CL.GD}}
for i,vi in ipairs(vipItems)do local vf=nw("Frame",{BackgroundColor3=Color3.fromRGB(40,30,0),Position=UDim2.new(0,10+(i-1)%2*285,0,viy),Size=UDim2.new(0,275,0,60),Parent=pVIP});cr(vf,8);local gl=nw("Frame",{BackgroundColor3=CL.GD,Position=UDim2.new(0,0,0,0),Size=UDim2.new(1,0,0,2),Parent=vf,BackgroundTransparency=0.3});spawn(function()while gl.Parent do wait(0.1)gl.Visible=not gl.Visible end end);nw("TextLabel",{Text=vi.n,TextSize=14,TextColor3=vi.c,Font=Enum.Font.GothamBold,BackgroundTransparency=1,Position=UDim2.new(0,10,0,4),Size=UDim2.new(0,255,0,22),Parent=vf});nw("TextLabel",{Text=vi.d,TextSize=11,TextColor3=CL.G,BackgroundTransparency=1,Position=UDim2.new(0,10,0,28),Size=UDim2.new(0,255,0,22),Parent=vf});if i%2==0 then viy=viy+68 end end
pVIP.CanvasSize=UDim2.new(0,0,0,viy+80)
NT("👑 Delta 至尊版 v5.0","15个标签页全部加载完成!",5)
TBB[1].BackgroundColor3=CL.P;TPP[1].Visible=true;curTab=1
print("至尊版全部加载完成!")